---

- name: set
  file:
    path: /etc/newrelic-infra.yml
    owner: root
    group: root
    state: touch

- name: set api key
  lineinfile:
    dest: /etc/newrelic-infra.yml
    regexp: 'license_key:'
    line: 'license_key:{{ newrelic_api_key  }}'

- name: install makecache
  yum: name=makecache enablerepo=newrelic-infra disablerepo=*

- name: install newrelic-infra
  yum: name=newrelic-infra
